name: Push Backend CRUD to GHCR
run-name: Release image ghcr
on: [push]
jobs:
  push-backend-crud-to-ghcr:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ghcr.io/${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}